### ISSUE TITLE
可以添加双眼模式么

### ISSUE THREAD

**Issue by chengxxxxwang** [zhudongyong/Panorama#4]
添加双眼模式和CoreMotion可以安放到GoogleCardBoard或者暴风魔镜上体验VR效果

**Comment by zhudongyong** [comment]
双眼模式是什么？陀螺仪是可以自定进去的

发自我的 iPhone

**Comment by chengxxxxwang** [comment]
![2469d7cf6bbb988b4634e5df31ee63a7](https://cloud.githubusercontent.com/assets/14540854/14939725/22b5a71c-0f86-11e6-87a0-2417969418d4.png)

**Comment by zhudongyong** [comment]
这个应该是能做，只是费用会有的贵

发自我的 iPhone

**Comment by chengxxxxwang** [comment]
..图片的我已经做出来了,现在正在尝试做视频播放的,视频播放的,成功的话,可以分享下.OC的话,顶多到这,VR技术再往下做就要用C++,U3D或者其他的东西了,我现在在关注UE4呢
